{{- if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: 80
{{- end }}
