{{- if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jk-webapp-frontend
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: http
{{- end }}
