apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.backendPort }}
