apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
  labels:
    app: backend
    release: kube-prometheus-stack
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.backendPort }}
