apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_NAME: "{{ .Values.config.dbName }}"
  DB_HOST: "{{ .Values.config.dbHost }}"
  DB_PORT: "{{ .Values.ports.dbPort }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS greetings (
      id SERIAL PRIMARY KEY,
      message TEXT NOT NULL
    );
    INSERT INTO greetings (message) VALUES ('Hello from the database!');
