apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      {{- if eq .Values.platform "minikube" }}
      nodePort: {{ .Values.service.frontendPort }}
      {{- end }}
