apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: myapp-database
  ports:
    - port: {{ .Values.service.dbPort }}
      targetPort: {{ .Values.service.dbPort }}
