apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: myapp-database
  ports:
    - port: {{ .Values.service.dbPort }}
      targetPort: {{ .Values.service.dbPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ if eq .Values.platform "minikube" }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: myapp-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      {{- if eq .Values.platform "minikube" }}
      nodePort: {{ .Values.service.frontendPort }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    namespace: {{ .Values.namespace }}
    app: myapp-backend
    release: kube-prometheus-stack
spec:
  type: {{ if eq .Values.platform "minikube" }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app: myapp-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      {{- if eq .Values.platform "minikube" }}
      nodePort: {{ .Values.service.backendPort }}
      {{- end }}
